[tool.poetry]
name = "opyapi"
version = "1.3.3"
description = "JsonSchem and OpenAPI tools for python."
authors = [
    "Dawid Kraczkowski <dawid.kraczkowski@gmail.com>"
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/kodemore/opyapi"
repository = "https://github.com/kodemore/opyapi"
documentation = "https://github.com/kodemore/opyapi"

keywords = ["JsonSchema", "OpenAPI", "validation", "json", "schema", "rest", "api"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]

# Requirements
[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^6.0.1"
cleo = "^2.0.1"

[tool.poetry.scripts]
opyapi="opyapi.console.application:main"

[tool.poetry.dev-dependencies]
pytest = "^4.1.0"
pytest-cov = "^2.5"
pytest-mock = "^1.9"
black = "^22.10.0"
isort = "^5.6.4"
mypy = "^0.812"
pylint = "^2.7.2"
